# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fibonacciseries',
            old_name='number',
            new_name='nterms',
        ),
        migrations.AddField(
            model_name='fibonacciseries',
            name='computation_time',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
