# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0002_auto_20160911_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacciseries',
            name='computation_time',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fibonacciseries',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
