# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0004_auto_20160911_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacciseries',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
